package com.hik.demo.dao.mapper;

import com.hik.demo.dao.pojo.HikDevice;
import com.hik.demo.dao.pojo.HikDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface HikDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int countByExample(HikDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int deleteByExample(HikDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int insert(HikDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int insertSelective(HikDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    List<HikDevice> selectByExample(HikDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    HikDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") HikDevice record, @Param("example") HikDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int updateByExample(@Param("record") HikDevice record, @Param("example") HikDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int updateByPrimaryKeySelective(HikDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hik_device
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    int updateByPrimaryKey(HikDevice record);

}