package com.hik.demo.dao.pojo;

import java.util.Date;

public class HikDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.id
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.device_name
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.device_no
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private String deviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.device_type
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.device_channel
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private String deviceChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.ctime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hik_device.utime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.id
     *
     * @return the value of hik_device.id
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.id
     *
     * @param id the value for hik_device.id
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.device_name
     *
     * @return the value of hik_device.device_name
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.device_name
     *
     * @param deviceName the value for hik_device.device_name
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.device_no
     *
     * @return the value of hik_device.device_no
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.device_no
     *
     * @param deviceNo the value for hik_device.device_no
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.device_type
     *
     * @return the value of hik_device.device_type
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.device_type
     *
     * @param deviceType the value for hik_device.device_type
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.device_channel
     *
     * @return the value of hik_device.device_channel
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public String getDeviceChannel() {
        return deviceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.device_channel
     *
     * @param deviceChannel the value for hik_device.device_channel
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setDeviceChannel(String deviceChannel) {
        this.deviceChannel = deviceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.ctime
     *
     * @return the value of hik_device.ctime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.ctime
     *
     * @param ctime the value for hik_device.ctime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hik_device.utime
     *
     * @return the value of hik_device.utime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hik_device.utime
     *
     * @param utime the value for hik_device.utime
     *
     * @mbggenerated Fri Aug 10 00:58:49 CST 2018
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}